### ISSUE TITLE
Question about Speaker ID Label

### ISSUE THREAD

**Issue by S-GH** [facebookresearch/voxpopuli#18]
Hi,

when I listened to the data labeled by speaker ID, I could hear what other speakers said even though it was the same speaker ID.

asr_en.tsv
id_|paragraph_id|session_id|**speaker_id**|original_text|normed_text|decoded|start_time|end_time|cer|wer|vad|split
speaker_id <- Is it unique id?

Thank you

**Comment by kahne** [comment]
Yes, they are unique and you can find the speaker profile at `https://www.europarl.europa.eu/meps/en/[speaker_id]`. Small heading/trailing overlaps may occur occasionally because the official cutting timestamps are not accurate (we calibrated them with speaker diarization but a few of them are still not perfect).

**Comment by S-GH** [comment]
I got it
Thank you a lot
